trigger:
- main

pool:
  name: pull1

steps:

# BUILD MAVEN PROJECT
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

# CREATE DEPLOYMENT FOLDER AND COPY JAR
- script: |
    echo Simulating deployment...
    cd $(Build.SourcesDirectory)

    if not exist deployed mkdir deployed

    copy target\*.jar deployed\

    echo Deployment successful!

    echo Contents of deployed folder:
    dir deployed
  displayName: 'Simulate Deployment'

# RUN THE JAR FILE
- script: |
    echo Running the JAR file...
    java -jar deployed\flipkart-app-1.0-SNAPSHOT.jar
  displayName: 'Run Application'